### ISSUE TITLE
Support for SSML

### ISSUE THREAD

**Issue by daniele-athome** [jeroenterheerdt/pycsspeechtts#14]
I've been using a patched version of your library to accept SSML in the text, but it's kind of hard-coded:

```patch
diff -rNu pycsspeechtts_old/pycsspeechtts.py pycsspeechtts/pycsspeechtts.py
--- pycsspeechtts_old/pycsspeechtts.py  2020-12-29 02:06:51.014818639 +0100
+++ pycsspeechtts/pycsspeechtts.py      2020-12-29 01:51:28.205551472 +0100
@@ -49,7 +49,7 @@
         prosody.set('volume', volume)
         prosody.set('pitch', pitch)
         prosody.set('contour', contour)
-        prosody.text = text
+        prosody.append(ElementTree.fromstring(text))

         headers = {"Content-Type": "application/ssml+xml",
                    "X-Microsoft-OutputFormat": output,
```

Would you accept a PR for this? It should be backwards compatible in some ways, but the text must be valid XML otherwise it will throw an exception. Or maybe add a boolean parameter (xml_text=True/False)? What do you think?

Thanks!

**Comment by jeroenterheerdt** [comment]
Happy to accept any PR that makes this component better!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by iridris** [comment]
Since the PR for this feature was merged, can a new release be tagged to bump up the version number?
