### ISSUE TITLE
Implementation of this code

### ISSUE THREAD

**Issue by jjku** [jeroenterheerdt/pycsspeechtts#16]
I am running core-2021.2.3 and supervisor-2021.02.9

I was wondering if this code was already implemented in those builds because I get the same error.

If it isn't implemented, is implementing this fix as simple as running the setup.py in my setup?

**Comment by jeroenterheerdt** [comment]
not sure what you are referring to - "this code"? "this fix"?

**Comment by jjku** [comment]
Oh yes. My apologies. Yes. This fix.

**Comment by jeroenterheerdt** [comment]
which fix?

**Comment by jjku** [comment]
Oh. sorry. It's the fix from this ticket - https://github.com/home-assistant/core/issues/15288 

I assumed that this was the latest for Home Assistant but I am still getting the same error that was on that ticket.

**Comment by jjku** [comment]
Sorry. I think I am mixing my issues up. For some odd reason I thought this python script was being used in Home Assistant..

**Comment by jeroenterheerdt** [comment]
it is being used in Home Assistant. I think we already fixed this issue, so it needs to be picked up by Home Assistant, that's it. Maybe you can test your scenario with this python package first?

**Comment by jjku** [comment]
Ok. That's where I am stuck. I don't know how to implement this package python into the Home Assistant setup.

Do I just run the setup.py?

**Comment by jeroenterheerdt** [comment]
no - either you test this python package separately and then overwrite the files, or wait until the fix makes it into the HA release.

**Comment by jjku** [comment]
That's what I was trying to do but I am hitting a roadblock. Ok. I'll wait for the fix as I cannot figure out where HA put the pycsspeechtts.py  files.
