### ISSUE TITLE
Moving forward to new Speech Services

### ISSUE THREAD

**Issue by keesschollaart81** [jeroenterheerdt/pycsspeechtts#2]
Hi Jeroen,

I tried to configure my Home Assistant for TTS via the Microsoft TTS Component. I failed because I configured an instance of a the new [speech services](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/overview) instead of the [bing text to speech service](https://docs.microsoft.com/en-us/azure/cognitive-services/Speech/api-reference-rest/bingvoiceoutput). I know the Cognitive Speech Services are still in preview but wanted to start the discussion on how to move forward. 

Do we need to build a new package like this? Do we need a second component in HA?

Shall I update [the HA docs](https://www.home-assistant.io/components/tts.microsoft/) to make the distinction between the new and old service more clear?

**Comment by jeroenterheerdt** [comment]
PR #3 has fixed this.
