### ISSUE TITLE
Release new package to PyPi

### ISSUE THREAD

**Issue by hmmbob** [jeroenterheerdt/pycsspeechtts#9]
Hi @jeroenterheerdt,

Would it be possible to release a new package to PyPi? That would include the changes from #4 (they aren't in the package yet) and would fix this issue in Home Assistant: https://github.com/home-assistant/core/issues/42809

As soon as you release 1.0.4, I'll ensure the Home Assistant integration gets updated to use it. Or, seeing that you are a HA user yourself as well; feel free to do so :)

Thanks!

**Comment by jeroenterheerdt** [comment]
done: https://pypi.org/project/pycsspeechtts/. Can you take care of updating HA to use this new version please?

**Comment by hmmbob** [comment]
Will do. Thanks much!
